In [11]:
import cv2
import numpy as np
import math

In [12]:
camera_intrinsics = np.array([[1430, 0, 620], 
                              [0, 1430, 480],
                              [0, 0,    1]], dtype=float)

camera_distortion = np.array([0, 0, 0, 0], dtype=float)

In [13]:
def R2YPR(R):
    sin_x = math.sqrt(R[2,0]*R[2,0] + R[2,1]*R[2,1])
    singular = sin_x < 1e-6
 
    if not singular:
        yaw = math.atan2(R[2,0], R[2,1])   
        pitch = math.atan2(sin_x, R[2,2])  
        roll = math.atan2(R[0,2], -R[1,2])  
    else: 
        yaw = 0                                  
        pitch = math.atan2(sin_x, R[2,2])    
        roll = 0 
    
    return np.array([yaw, pitch, roll])

In [14]:
def rad2deg(ypr_vec):
    for i in range(0, len(ypr_vec)):
        ypr_vec[i] *= -180/math.pi
    return ypr_vec

In [15]:
stream = cv2.VideoCapture(0)

while(True):
    ret, frame = stream.read()
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    
    aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_6X6_250)
    parameters = cv2.aruco.DetectorParameters_create()
    corners, ids, rejectedImgPoints = cv2.aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
    
    frame_markers = frame
    if np.all(ids is not None):
        for i in range(0, len(ids)):
            rvec, tvec, markerPoints = cv2.aruco.estimatePoseSingleMarkers(corners[i], 0.8, camera_intrinsics, camera_distortion)
            (rvec - tvec).any() 
            cv2.aruco.drawDetectedMarkers(frame_markers, corners)
            cv2.drawFrameAxes(frame_markers, camera_intrinsics, camera_distortion, rvec, tvec, 0.5, 2)
            rmat = np.zeros((3, 3))
            cv2.Rodrigues(rvec, rmat)
            
            ypr_rad = R2YPR(rmat)
            ypr_deg = rad2deg(ypr_rad)
            # print('yaw: ', ypr_deg[0], 'pitch: ', ypr_deg[1], 'roll: ', ypr_deg[2])
            # print('x: ', tvec[0], 'y: ', tvec[1], 'z: ', tvec[2])
            print(tvec)
            # print('shit', rmat)
                
    cv2.imshow('Markers', frame_markers)
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

cv2.destroyAllWindows()

[[[-1.71693591 -0.67874233 10.11240497]]]
[[[-1.71693591 -0.67874233 10.11240497]]]
[[[-1.45874828 -0.84640214 10.2833491 ]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49297696 -0.9014351  10.35915741]]]
[[[-1.49190165 -0.90225182 10.32650989]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49190165 -0.90225182 10.32650989]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49801752 -0.90515441 10.38174686]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49870676 -0.90734366 10.38577935]]]
[[[-1.49870676 -0.90734366 10.3857